FROM node:16

# ENV DEBUG true

RUN mkdir /app
COPY ./frontend /app
WORKDIR /app
RUN DEBIAN_FRONTEND='noninteractive' apt-get update
RUN DEBIAN_FRONTEND='noninteractive' apt-get upgrade -y
RUN DEBIAN_FRONTEND='noninteractive' apt-get install -y --no-install-recommends \
    python3 \
    git \
    make \
    gcc \
    g++ \
    nano \
    && rm -rf /var/lib/apt/lists/*

RUN npm install
RUN npm i -g nodemon

ENTRYPOINT yarn start
