# FROM tiangolo/uvicorn-gunicorn-fastapi:python3.8
FROM python:3.8-slim-buster

RUN mkdir /backend
WORKDIR /backend

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONBUFFERED 1

# install system dependencies
RUN apt-get update \
  && apt-get -y install netcat gcc postgresql nano \
  && apt-get clean

# install python dependencies
RUN pip install --upgrade pip
COPY ./backend/requirements.txt .
RUN pip install -r requirements.txt

COPY ./backend /backend