version: '3.7'

services:
  aggregator:
    build:
      context: .
      dockerfile: ../Dockerfile.aggregator
    container_name: aggregator
    volumes:
      - ./app:/app # !! update for main docker-compose file
    # env_file:
    #   - ./aggregator/.env
    ports:
      - 8000:8000
    # command: uvicorn main:app --reload --workers 4 --reload-dir /app --host 0.0.0.0 --port 8000

  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379

  worker:
    build:
      context: .
      dockerfile: ../Dockerfile.aggregator
    container_name: worker
    command: celery --app app.tasks worker --loglevel=DEBUG -Q main-queue -c 1

  flower:  
    image: mher/flower
    container_name: flower
    command: celery flower --broker=redis://redis:6379/0 --port=5555
    ports:  
        - 5555:5555
    depends_on:
      - redis

